spring.datasource.url=jdbc:postgresql://localhost:5433/debbo_collect
spring.datasource.username=postgres
spring.datasource.password=postgres



spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog-master.yaml

spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none

