-- liquibase formatted sql

-- =========================================================
-- TABLE UTILISATEUR
-- =========================================================

-- changeset Mody:create-utilisateur-table
CREATE TABLE utilisateur
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255),
    prenom VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(100),
    superviseur_id BIGINT,
    CONSTRAINT utilisateur_pkey PRIMARY KEY (id)

);

ALTER TABLE utilisateur
    ADD CONSTRAINT fk_superviseur
        FOREIGN KEY (superviseur_id)
            REFERENCES utilisateur(id);



-- =========================================================
-- TABLE PROJET
-- =========================================================

-- changeset Mody:create-projet-table
CREATE TABLE projet
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255),
    description VARCHAR(255),
    zone_geographique VARCHAR(255),
    date_debut DATE,
    date_fin DATE,
    type VARCHAR(255),

    superviseur_id BIGINT,
    bailleur_id BIGINT,

    CONSTRAINT projet_pkey PRIMARY KEY (id),

    CONSTRAINT fk_projet_superviseur
        FOREIGN KEY (superviseur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_projet_bailleur
        FOREIGN KEY (bailleur_id)
            REFERENCES utilisateur(id)
);

-- =========================================================
-- TABLE CHAMP
-- =========================================================

-- changeset Mody:create-champ-table
CREATE TABLE champ
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255),
    question VARCHAR(255),
    preuve_obligatoire BOOLEAN,

    projet_id BIGINT,

    CONSTRAINT champ_pkey PRIMARY KEY (id),

    CONSTRAINT fk_champ_projet
        FOREIGN KEY (projet_id)
            REFERENCES projet(id)
);

-- =========================================================
-- TABLE COLLECTE
-- =========================================================

-- changeset Mody:create-collecte-table
CREATE TABLE collecte
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_collecte DATE,
    localisation VARCHAR(255),

    enqueteur_id BIGINT,
    projet_id BIGINT,

    CONSTRAINT collecte_pkey PRIMARY KEY (id),

    CONSTRAINT fk_collecte_enqueteur
        FOREIGN KEY (enqueteur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_collecte_projet
        FOREIGN KEY (projet_id)
            REFERENCES projet(id)
);

-- =========================================================
-- TABLE REPONSE
-- =========================================================

-- changeset Mody:create-reponse-table
CREATE TABLE reponse
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valeur VARCHAR(255),

    champ_id BIGINT,
    collecte_id BIGINT,

    CONSTRAINT reponse_pkey PRIMARY KEY (id),

    CONSTRAINT fk_reponse_champ
        FOREIGN KEY (champ_id)
            REFERENCES champ(id),

    CONSTRAINT fk_reponse_collecte
        FOREIGN KEY (collecte_id)
            REFERENCES collecte(id)
);

-- =========================================================
-- TABLE MEDIA
-- =========================================================

-- changeset Mody:create-media-table
CREATE TABLE media
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255),
    url VARCHAR(255),

    reponse_id BIGINT,

    CONSTRAINT media_pkey PRIMARY KEY (id),

    CONSTRAINT fk_media_reponse
        FOREIGN KEY (reponse_id)
            REFERENCES reponse(id)
);

-- =========================================================
-- TABLE MESSAGE
-- =========================================================

-- changeset Mody:create-message-table
CREATE TABLE message
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contenu VARCHAR(255),
    date_envoi DATE,
    lu BOOLEAN,

    expediteur_id BIGINT,
    destinataire_id BIGINT,

    CONSTRAINT message_pkey PRIMARY KEY (id),

    CONSTRAINT fk_message_expediteur
        FOREIGN KEY (expediteur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_message_destinataire
        FOREIGN KEY (destinataire_id)
            REFERENCES utilisateur(id)
);
-- changeset Mody:add-geolocalisation-to-collecte

ALTER TABLE collecte
    ADD COLUMN latitude DOUBLE PRECISION;

ALTER TABLE collecte
    ADD COLUMN longitude DOUBLE PRECISION;

-- changeset Mody:add-statut-to-collecte

ALTER TABLE collecte
    ADD COLUMN statut VARCHAR(50);

-- changeset Mody:add-compte-actif-to-utilisateur

ALTER TABLE utilisateur
    ADD COLUMN compte_actif BOOLEAN DEFAULT FALSE;

-- changeset Mody:add-projet-id-to-utilisateur

ALTER TABLE utilisateur
    ADD COLUMN projet_id BIGINT;

ALTER TABLE utilisateur
    ADD CONSTRAINT fk_utilisateur_projet
        FOREIGN KEY (projet_id)
            REFERENCES projet(id);

-- changeset Mody:create-lot-collecte

CREATE TABLE lot_collecte
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_envoi DATE,
    statut VARCHAR(50),

    enqueteur_id BIGINT,
    projet_id BIGINT,

    CONSTRAINT lot_collecte_pkey PRIMARY KEY (id),

    CONSTRAINT fk_lot_enqueteur
        FOREIGN KEY (enqueteur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_lot_projet
        FOREIGN KEY (projet_id)
            REFERENCES projet(id)
);

-- changeset Mody:add-lot-to-collecte

ALTER TABLE collecte
    ADD COLUMN lot_collecte_id BIGINT;

ALTER TABLE collecte
    ADD CONSTRAINT fk_collecte_lot
        FOREIGN KEY (lot_collecte_id)
            REFERENCES lot_collecte(id);

-- changeset Mody:add-commentaire-superviseur-to-reponse

ALTER TABLE reponse
    ADD COLUMN commentaire_superviseur VARCHAR(1000);

-- changeset Mody:add-colum-numero-collect-projet
ALTER TABLE collecte
    ADD COLUMN numero_collecte_projet INTEGER;
-- changeset Mody:add-colum-date-envoie-bailleur
ALTER TABLE projet
    ADD COLUMN date_envoi_bailleur TIMESTAMP;
-- changeset Mody:add-colum-date-validation
ALTER TABLE collecte
    ADD COLUMN date_validation TIMESTAMP;
-- changeset Mody:add-colum-option
ALTER TABLE champ ADD COLUMN options TEXT;

-- changeset Mody:add-type-statistique-to-champ

ALTER TABLE champ
    ADD COLUMN type_statistique VARCHAR(50) DEFAULT 'AUCUNE';

-- changeset Mody:add-unique-email-utilisateur
CREATE UNIQUE INDEX uk_utilisateur_email_lower
    ON utilisateur (LOWER(email));

-- changeset Mody:create-superviseur-bailleur-table
CREATE TABLE superviseur_bailleur
(
    superviseur_id BIGINT NOT NULL,
    bailleur_id BIGINT NOT NULL,

    CONSTRAINT superviseur_bailleur_pkey
        PRIMARY KEY (superviseur_id, bailleur_id),

    CONSTRAINT fk_superviseur_bailleur_superviseur
        FOREIGN KEY (superviseur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_superviseur_bailleur_bailleur
        FOREIGN KEY (bailleur_id)
            REFERENCES utilisateur(id)
);

-- changeset Mody:fill-superviseur-bailleur-from-projets
INSERT INTO superviseur_bailleur (
    superviseur_id,
    bailleur_id
)
SELECT DISTINCT
    superviseur_id,
    bailleur_id
FROM projet
WHERE superviseur_id IS NOT NULL
  AND bailleur_id IS NOT NULL
    ON CONFLICT (superviseur_id, bailleur_id)
DO NOTHING;

-- changeset Mody:add-statut-to-projet
ALTER TABLE projet
    ADD COLUMN statut VARCHAR(50)
        NOT NULL
        DEFAULT 'EN_COURS';

-- changeset Mody:add-condition-to-champ
ALTER TABLE champ
    ADD COLUMN champ_parent_id BIGINT;

ALTER TABLE champ
    ADD COLUMN valeur_declenchement VARCHAR(255);

ALTER TABLE champ
    ADD CONSTRAINT fk_champ_parent
        FOREIGN KEY (champ_parent_id)
            REFERENCES champ(id);
