-- liquibase formatted sql

-- =========================================================
-- TABLE UTILISATEUR
-- =========================================================

-- changeset Mody:create-utilisateur-table
CREATE TABLE utilisateur
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255),
    prenom VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(100),

    CONSTRAINT utilisateur_pkey PRIMARY KEY (id)
);

-- =========================================================
-- TABLE PROJET
-- =========================================================

-- changeset Mody:create-projet-table
CREATE TABLE projet
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255),
    description VARCHAR(255),
    zone_geographique VARCHAR(255),
    date_debut DATE,
    date_fin DATE,
    type VARCHAR(255),

    superviseur_id BIGINT,
    bailleur_id BIGINT,

    CONSTRAINT projet_pkey PRIMARY KEY (id),

    CONSTRAINT fk_projet_superviseur
        FOREIGN KEY (superviseur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_projet_bailleur
        FOREIGN KEY (bailleur_id)
            REFERENCES utilisateur(id)
);

-- =========================================================
-- TABLE CHAMP
-- =========================================================

-- changeset Mody:create-champ-table
CREATE TABLE champ
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255),
    question VARCHAR(255),
    preuve_obligatoire BOOLEAN,

    projet_id BIGINT,

    CONSTRAINT champ_pkey PRIMARY KEY (id),

    CONSTRAINT fk_champ_projet
        FOREIGN KEY (projet_id)
            REFERENCES projet(id)
);

-- =========================================================
-- TABLE COLLECTE
-- =========================================================

-- changeset Mody:create-collecte-table
CREATE TABLE collecte
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_collecte DATE,
    localisation VARCHAR(255),

    enqueteur_id BIGINT,
    projet_id BIGINT,

    CONSTRAINT collecte_pkey PRIMARY KEY (id),

    CONSTRAINT fk_collecte_enqueteur
        FOREIGN KEY (enqueteur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_collecte_projet
        FOREIGN KEY (projet_id)
            REFERENCES projet(id)
);

-- =========================================================
-- TABLE REPONSE
-- =========================================================

-- changeset Mody:create-reponse-table
CREATE TABLE reponse
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valeur VARCHAR(255),

    champ_id BIGINT,
    collecte_id BIGINT,

    CONSTRAINT reponse_pkey PRIMARY KEY (id),

    CONSTRAINT fk_reponse_champ
        FOREIGN KEY (champ_id)
            REFERENCES champ(id),

    CONSTRAINT fk_reponse_collecte
        FOREIGN KEY (collecte_id)
            REFERENCES collecte(id)
);

-- =========================================================
-- TABLE MEDIA
-- =========================================================

-- changeset Mody:create-media-table
CREATE TABLE media
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255),
    url VARCHAR(255),

    reponse_id BIGINT,

    CONSTRAINT media_pkey PRIMARY KEY (id),

    CONSTRAINT fk_media_reponse
        FOREIGN KEY (reponse_id)
            REFERENCES reponse(id)
);

-- =========================================================
-- TABLE MESSAGE
-- =========================================================

-- changeset Mody:create-message-table
CREATE TABLE message
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contenu VARCHAR(255),
    date_envoi DATE,
    lu BOOLEAN,

    expediteur_id BIGINT,
    destinataire_id BIGINT,

    CONSTRAINT message_pkey PRIMARY KEY (id),

    CONSTRAINT fk_message_expediteur
        FOREIGN KEY (expediteur_id)
            REFERENCES utilisateur(id),

    CONSTRAINT fk_message_destinataire
        FOREIGN KEY (destinataire_id)
            REFERENCES utilisateur(id)
);